favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://practice.dev/themes/drupaltheme/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  drupaltheme: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
cdn_jsdelivr_theme: united
table_responsive: '-1'
table: ''
